### ISSUE TITLE
Project Process

### ISSUE THREAD

**Issue by huangfengye** [FotatoPotato/Artix-Express-35#1]
Hi, is this project still alive?? Will it update in future

**Comment by FotatoPotato** [comment]
No, not anymore. I started this project before University but since then I have had all my time taken by work and classes. Sorry.

From: huangfengye ***@***.***>
Sent: Tuesday, December 21, 2021 7:18 PM
To: FotatoPotato/Artix-Express-35 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [FotatoPotato/Artix-Express-35] Project Process (Issue #1)


Hi, is this project still alive?? Will it update in future

-
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFotatoPotato%2FArtix-Express-35%2Fissues%2F1&data=04%7C01%7C%7C840fd2733b8341e5d61b08d9c4f99db0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637757398635185349%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5tewkhM6YAWo93gAumILaRJJfCuEMflFKwxlte3M6I0%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACT54DL6G7KYEQKUXTOYAHTUSE7NLANCNFSM5KRSMXOA&data=04%7C01%7C%7C840fd2733b8341e5d61b08d9c4f99db0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637757398635185349%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5qWih138rPw51brO1RQWLBtRuS8GfXknVhByXSK2bik%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C840fd2733b8341e5d61b08d9c4f99db0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637757398635185349%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8TUMDfZByADepuJtJJrVKjQZEkYdHTiC9WJJczV0l8E%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C840fd2733b8341e5d61b08d9c4f99db0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637757398635185349%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cSNpznR%2FlIh6MAj%2FRHaDyvwTXWYlWX6C7GNLFkqk%2Fj0%3D&reserved=0>.

**Comment by huangfengye** [comment]
thank you.
